spring.application.name=jobapp
# spring.datasource.url: the address of your database  
# localhost:3306 : my sql running on your computer at port 3306
# jobapp-> the database you created
spring.datasource.url=jdbc:mysql://localhost:3306/jobapp

# MySQL username(root by default)
spring.datasource.username=root

# your MySQL password
spring.datasource.password=anant1652006

# the below full line tells spring which driver to use to connect to MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# the below line tells Hibernate to automatically create/update tables based on you java classes-> you do not need to write CREATE TABLES SQL manually .
spring.jpa.hibernate.ddl-auto=update

# the below line tells: show the SQL queries Hibernate generates in you terminal -> very useful for learning and debugging 
spring.jpa.show-sql=true

# the below lines tells Hibernate you are using MySql specifiaclly->So it generates MySQL compatible SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect